# https://developers.google.com/appengine/docs/python/config/appconfig

application: tremily-wedding
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /static
  static_dir: static

- url: .*  # This regex directs all routes to main.app
  script: main.app
